# Generated by Django 3.1.2 on 2020-10-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201009_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='maximum',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
