# Generated by Django 3.1.2 on 2020-10-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20201011_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='children',
            new_name='Student',
        ),
    ]
