# Generated by Django 3.1.2 on 2020-10-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_auto_20201014_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='Student',
            new_name='children',
        ),
    ]
