# Generated by Django 3.1.2 on 2020-10-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20201014_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
