# Generated by Django 3.1.2 on 2020-10-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20201011_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
