# Generated by Django 3.1.2 on 2020-10-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_seminar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
