# Generated by Django 3.1.2 on 2020-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
