# Generated by Django 3.1.2 on 2020-10-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_attachment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='thumbnail',
        ),
    ]
