# Generated by Django 3.1.2 on 2020-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_remove_file_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='max_score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.TextField(default='Amortized Analysis', max_length=300),
            preserve_default=False,
        ),
    ]
