# Generated by Django 3.1.2 on 2020-10-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_remove_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_timestamp_end',
            field=models.TimeField(blank=None, null=True),
        ),
    ]
