# Generated by Django 3.1.2 on 2020-10-12 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_quiz_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='enable',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
