# Generated by Django 3.1.2 on 2020-10-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20201011_1854'),
        ('Course', '0011_upload_seminar_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.course'),
            preserve_default=False,
        ),
    ]
