# Generated by Django 3.1.2 on 2020-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_upload_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='message_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.message'),
        ),
    ]
