# Generated by Django 3.1.2 on 2020-10-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_event_event_timestamp_end'),
        ('Course', '0013_upload_message_upload'),
    ]

    operations = [
    ]
