# Generated by Django 3.1.2 on 2020-10-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_comment_timestamp'),
        ('Course', '0014_merge_20201013_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='post_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.post'),
        ),
    ]
