# Generated by Django 3.1.2 on 2020-10-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0017_assignment_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='assignments'),
        ),
    ]
