# Generated by Django 3.1.2 on 2020-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0018_assignment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='submissions'),
        ),
    ]
