# Generated by Django 3.1.2 on 2020-10-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0019_submissions_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='assignment_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.assignment'),
        ),
    ]
