# Generated by Django 3.1.2 on 2020-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0020_upload_assignment_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.TextField(default='www.youtube.com', max_length=100),
            preserve_default=False,
        ),
    ]
